DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  total_cost INTEGER NOT NULL DEFAULT 0,

  placed_at TIMESTAMP NOT NULL DEFAULT 0,
  accepted_at TIMESTAMP NOT NULL DEFAULT 0,
  completed_at TIMESTAMP NOT NULL DEFAULT 0,
  time_to_comeplete INTEGER NOT NULL DEFAULT 0,

  is_active BOOLEAN NOT NULL DEFAULT TRUE
);
