
DROP TABLE IF EXISTS cart_items CASCADE;
CREATE TABLE cart_items (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  menu_item_id INTEGER REFERENCES menu_items(id) ON DELETE CASCADE,

  quantity SMALLINT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);
